/*
 * vsq3.cs
 * Copyright c 2018 yo_xxx
 *
 * This file is part of TI2VSQX.
 *
 * TI2VSQX is free software; you can redistribute it and/or
 * modify it under the terms of the BSD License.
 *
 * TI2VSQX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
using System;
using System.Collections.Generic;
using System.Text;
using System.Xml;

namespace TI2VSQX
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vsq3
    {

        private string venderField;

        private string versionField;

        private vVoice[] vVoiceTableField;

        private mixer mixerField;

        private masterTrack masterTrackField;

        private vsTrack[] vsTrackField;

        private wavPart[] seTrackField;

        private wavPart[] karaokeTrackField;

        private aux[] auxField;

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection vender
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.venderField);
            }
            set
            {
                this.venderField = value.Value;
            }
        }
        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection version
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.versionField);
            }
            set
            {
                this.versionField = value.Value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vVoice", IsNullable = false)]
        public vVoice[] vVoiceTable
        {
            get
            {
                return this.vVoiceTableField;
            }
            set
            {
                this.vVoiceTableField = value;
            }
        }

        /// <remarks/>
        public mixer mixer
        {
            get
            {
                return this.mixerField;
            }
            set
            {
                this.mixerField = value;
            }
        }

        /// <remarks/>
        public masterTrack masterTrack
        {
            get
            {
                return this.masterTrackField;
            }
            set
            {
                this.masterTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vsTrack")]
        public vsTrack[] vsTrack
        {
            get
            {
                return this.vsTrackField;
            }
            set
            {
                this.vsTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("wavPart", IsNullable = false)]
        public wavPart[] seTrack
        {
            get
            {
                return this.seTrackField;
            }
            set
            {
                this.seTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("wavPart", IsNullable = false)]
        public wavPart[] karaokeTrack
        {
            get
            {
                return this.karaokeTrackField;
            }
            set
            {
                this.karaokeTrackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aux")]
        public aux[] aux
        {
            get
            {
                return this.auxField;
            }
            set
            {
                this.auxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vVoice
    {

        private byte vBSField;

        private byte vPCField;

        private string compIDField;

        private string vVoiceNameField;

        private vVoiceParam vVoiceParamField;

        /// <remarks/>
        public byte vBS
        {
            get
            {
                return this.vBSField;
            }
            set
            {
                this.vBSField = value;
            }
        }

        /// <remarks/>
        public byte vPC
        {
            get
            {
                return this.vPCField;
            }
            set
            {
                this.vPCField = value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection compID
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.compIDField);
            }
            set
            {
                this.compIDField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection vVoiceName
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.vVoiceNameField);
            }
            set
            {
                this.vVoiceNameField = value.Value;
            }
        }

        /// <remarks/>
        public vVoiceParam vVoiceParam
        {
            get
            {
                return this.vVoiceParamField;
            }
            set
            {
                this.vVoiceParamField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vVoiceParam
    {

        private sbyte breField;

        private sbyte briField;

        private sbyte cleField;

        private sbyte genField;

        private sbyte opeField;

        /// <remarks/>
        public sbyte bre
        {
            get
            {
                return this.breField;
            }
            set
            {
                this.breField = value;
            }
        }

        /// <remarks/>
        public sbyte bri
        {
            get
            {
                return this.briField;
            }
            set
            {
                this.briField = value;
            }
        }

        /// <remarks/>
        public sbyte cle
        {
            get
            {
                return this.cleField;
            }
            set
            {
                this.cleField = value;
            }
        }

        /// <remarks/>
        public sbyte gen
        {
            get
            {
                return this.genField;
            }
            set
            {
                this.genField = value;
            }
        }

        /// <remarks/>
        public sbyte ope
        {
            get
            {
                return this.opeField;
            }
            set
            {
                this.opeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    public partial class typePhonemes
    {

        private byte lockField;

        private bool lockFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte @lock
        {
            get
            {
                return this.lockField;
            }
            set
            {
                this.lockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockSpecified
        {
            get
            {
                return this.lockFieldSpecified;
            }
            set
            {
                this.lockFieldSpecified = value;
            }
        }

        // データの設定・取得用
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }

        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    public partial class typeParamAttr
    {

        private string idField;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class mixer
    {

        private masterUnit masterUnitField;

        private vsUnit[] vsUnitField;

        private seUnit seUnitField;

        private karaokeUnit karaokeUnitField;

        /// <remarks/>
        public masterUnit masterUnit
        {
            get
            {
                return this.masterUnitField;
            }
            set
            {
                this.masterUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vsUnit")]
        public vsUnit[] vsUnit
        {
            get
            {
                return this.vsUnitField;
            }
            set
            {
                this.vsUnitField = value;
            }
        }

        /// <remarks/>
        public seUnit seUnit
        {
            get
            {
                return this.seUnitField;
            }
            set
            {
                this.seUnitField = value;
            }
        }

        /// <remarks/>
        public karaokeUnit karaokeUnit
        {
            get
            {
                return this.karaokeUnitField;
            }
            set
            {
                this.karaokeUnitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class masterUnit
    {

        private short outDevField;

        private vstPlugin[] vstPluginField;

        private vstPluginSR vstPluginSRField;

        private int retLevelField;

        private int volField;

        /// <remarks/>
        public short outDev
        {
            get
            {
                return this.outDevField;
            }
            set
            {
                this.outDevField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vstPlugin")]
        public vstPlugin[] vstPlugin
        {
            get
            {
                return this.vstPluginField;
            }
            set
            {
                this.vstPluginField = value;
            }
        }

        /// <remarks/>
        public vstPluginSR vstPluginSR
        {
            get
            {
                return this.vstPluginSRField;
            }
            set
            {
                this.vstPluginSRField = value;
            }
        }

        /// <remarks/>
        public int retLevel
        {
            get
            {
                return this.retLevelField;
            }
            set
            {
                this.retLevelField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vstPlugin
    {

        private string vstPluginIDField;

        private string vstPluginNameField;

        private byte vstSDKVersionField;

        private int vstParamNumField;

        private int[] vstParamValField;

        private int vstPresetNoField;

        private bool vstPresetNoFieldSpecified;

        private byte enableField;

        private byte bypassField;

        /// <remarks/>
        public string vstPluginID
        {
            get
            {
                return this.vstPluginIDField;
            }
            set
            {
                this.vstPluginIDField = value;
            }
        }

        /// <remarks/>
        public string vstPluginName
        {
            get
            {
                return this.vstPluginNameField;
            }
            set
            {
                this.vstPluginNameField = value;
            }
        }

        /// <remarks/>
        public byte vstSDKVersion
        {
            get
            {
                return this.vstSDKVersionField;
            }
            set
            {
                this.vstSDKVersionField = value;
            }
        }

        /// <remarks/>
        public int vstParamNum
        {
            get
            {
                return this.vstParamNumField;
            }
            set
            {
                this.vstParamNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("val", IsNullable = false)]
        public int[] vstParamVal
        {
            get
            {
                return this.vstParamValField;
            }
            set
            {
                this.vstParamValField = value;
            }
        }

        /// <remarks/>
        public int vstPresetNo
        {
            get
            {
                return this.vstPresetNoField;
            }
            set
            {
                this.vstPresetNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vstPresetNoSpecified
        {
            get
            {
                return this.vstPresetNoFieldSpecified;
            }
            set
            {
                this.vstPresetNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public byte enable
        {
            get
            {
                return this.enableField;
            }
            set
            {
                this.enableField = value;
            }
        }

        /// <remarks/>
        public byte bypass
        {
            get
            {
                return this.bypassField;
            }
            set
            {
                this.bypassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vstPluginSR
    {

        private string vstPluginIDField;

        private string vstPluginNameField;

        private byte vstSDKVersionField;

        private int vstParamNumField;

        private int[] vstParamValField;

        private int vstPresetNoField;

        private bool vstPresetNoFieldSpecified;

        private byte enableField;

        private byte bypassField;

        /// <remarks/>
        public string vstPluginID
        {
            get
            {
                return this.vstPluginIDField;
            }
            set
            {
                this.vstPluginIDField = value;
            }
        }

        /// <remarks/>
        public string vstPluginName
        {
            get
            {
                return this.vstPluginNameField;
            }
            set
            {
                this.vstPluginNameField = value;
            }
        }

        /// <remarks/>
        public byte vstSDKVersion
        {
            get
            {
                return this.vstSDKVersionField;
            }
            set
            {
                this.vstSDKVersionField = value;
            }
        }

        /// <remarks/>
        public int vstParamNum
        {
            get
            {
                return this.vstParamNumField;
            }
            set
            {
                this.vstParamNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("val", IsNullable = false)]
        public int[] vstParamVal
        {
            get
            {
                return this.vstParamValField;
            }
            set
            {
                this.vstParamValField = value;
            }
        }

        /// <remarks/>
        public int vstPresetNo
        {
            get
            {
                return this.vstPresetNoField;
            }
            set
            {
                this.vstPresetNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vstPresetNoSpecified
        {
            get
            {
                return this.vstPresetNoFieldSpecified;
            }
            set
            {
                this.vstPresetNoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public byte enable
        {
            get
            {
                return this.enableField;
            }
            set
            {
                this.enableField = value;
            }
        }

        /// <remarks/>
        public byte bypass
        {
            get
            {
                return this.bypassField;
            }
            set
            {
                this.bypassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vsUnit
    {

        private byte vsTrackNoField;

        private int inGainField;

        private vstPlugin[] vstPluginField;

        private int sendLevelField;

        private byte sendEnableField;

        private byte muteField;

        private byte soloField;

        private int panField;

        private int volField;

        /// <remarks/>
        public byte vsTrackNo
        {
            get
            {
                return this.vsTrackNoField;
            }
            set
            {
                this.vsTrackNoField = value;
            }
        }

        /// <remarks/>
        public int inGain
        {
            get
            {
                return this.inGainField;
            }
            set
            {
                this.inGainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vstPlugin")]
        public vstPlugin[] vstPlugin
        {
            get
            {
                return this.vstPluginField;
            }
            set
            {
                this.vstPluginField = value;
            }
        }

        /// <remarks/>
        public int sendLevel
        {
            get
            {
                return this.sendLevelField;
            }
            set
            {
                this.sendLevelField = value;
            }
        }

        /// <remarks/>
        public byte sendEnable
        {
            get
            {
                return this.sendEnableField;
            }
            set
            {
                this.sendEnableField = value;
            }
        }

        /// <remarks/>
        public byte mute
        {
            get
            {
                return this.muteField;
            }
            set
            {
                this.muteField = value;
            }
        }

        /// <remarks/>
        public byte solo
        {
            get
            {
                return this.soloField;
            }
            set
            {
                this.soloField = value;
            }
        }

        /// <remarks/>
        public int pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class seUnit
    {

        private int inGainField;

        private vstPlugin[] vstPluginField;

        private int sendLevelField;

        private byte sendEnableField;

        private byte muteField;

        private byte soloField;

        private int panField;

        private int volField;

        /// <remarks/>
        public int inGain
        {
            get
            {
                return this.inGainField;
            }
            set
            {
                this.inGainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vstPlugin")]
        public vstPlugin[] vstPlugin
        {
            get
            {
                return this.vstPluginField;
            }
            set
            {
                this.vstPluginField = value;
            }
        }

        /// <remarks/>
        public int sendLevel
        {
            get
            {
                return this.sendLevelField;
            }
            set
            {
                this.sendLevelField = value;
            }
        }

        /// <remarks/>
        public byte sendEnable
        {
            get
            {
                return this.sendEnableField;
            }
            set
            {
                this.sendEnableField = value;
            }
        }

        /// <remarks/>
        public byte mute
        {
            get
            {
                return this.muteField;
            }
            set
            {
                this.muteField = value;
            }
        }

        /// <remarks/>
        public byte solo
        {
            get
            {
                return this.soloField;
            }
            set
            {
                this.soloField = value;
            }
        }

        /// <remarks/>
        public int pan
        {
            get
            {
                return this.panField;
            }
            set
            {
                this.panField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class karaokeUnit
    {

        private int inGainField;

        private vstPlugin[] vstPluginField;

        private byte muteField;

        private byte soloField;

        private int volField;

        /// <remarks/>
        public int inGain
        {
            get
            {
                return this.inGainField;
            }
            set
            {
                this.inGainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vstPlugin")]
        public vstPlugin[] vstPlugin
        {
            get
            {
                return this.vstPluginField;
            }
            set
            {
                this.vstPluginField = value;
            }
        }

        /// <remarks/>
        public byte mute
        {
            get
            {
                return this.muteField;
            }
            set
            {
                this.muteField = value;
            }
        }

        /// <remarks/>
        public byte solo
        {
            get
            {
                return this.soloField;
            }
            set
            {
                this.soloField = value;
            }
        }

        /// <remarks/>
        public int vol
        {
            get
            {
                return this.volField;
            }
            set
            {
                this.volField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class masterTrack
    {

        private string seqNameField;

        private string commentField;

        private ushort resolutionField;

        private byte preMeasureField;

        private timeSig[] timeSigField;

        private tempo[] tempoField;

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection seqName
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.seqNameField);
            }
            set
            {
                this.seqNameField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection comment
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.commentField);
            }
            set
            {
                this.commentField = value.Value;
            }
        }

        /// <remarks/>
        public ushort resolution
        {
            get
            {
                return this.resolutionField;
            }
            set
            {
                this.resolutionField = value;
            }
        }

        /// <remarks/>
        public byte preMeasure
        {
            get
            {
                return this.preMeasureField;
            }
            set
            {
                this.preMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("timeSig")]
        public timeSig[] timeSig
        {
            get
            {
                return this.timeSigField;
            }
            set
            {
                this.timeSigField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tempo")]
        public tempo[] tempo
        {
            get
            {
                return this.tempoField;
            }
            set
            {
                this.tempoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class timeSig
    {

        private int posMesField;

        private byte numeField;

        private byte denomiField;

        /// <remarks/>
        public int posMes
        {
            get
            {
                return this.posMesField;
            }
            set
            {
                this.posMesField = value;
            }
        }

        /// <remarks/>
        public byte nume
        {
            get
            {
                return this.numeField;
            }
            set
            {
                this.numeField = value;
            }
        }

        /// <remarks/>
        public byte denomi
        {
            get
            {
                return this.denomiField;
            }
            set
            {
                this.denomiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class tempo
    {

        private int posTickField;

        private int bpmField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public int bpm
        {
            get
            {
                return this.bpmField;
            }
            set
            {
                this.bpmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vsTrack
    {

        private byte vsTrackNoField;

        private string trackNameField;

        private string commentField;

        private object[] itemsField;

        /// <remarks/>
        public byte vsTrackNo
        {
            get
            {
                return this.vsTrackNoField;
            }
            set
            {
                this.vsTrackNoField = value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection trackName
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.trackNameField);
            }
            set
            {
                this.trackNameField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection comment
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.commentField);
            }
            set
            {
                this.commentField = value.Value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("musicalPart", typeof(musicalPart))]
        [System.Xml.Serialization.XmlElementAttribute("prosodyPart", typeof(prosodyPart))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class musicalPart
    {

        private int posTickField;

        private int playTimeField;

        private string partNameField;

        private string commentField;

        private stylePlugin stylePluginField;

        private typeParamAttr[] partStyleField;

        private phraseStyle[] phraseStyleField;

        private singer[] singerField;

        private mCtrl[] mCtrlField;

        private sCtrl[] sCtrlField;

        private note[] noteField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public int playTime
        {
            get
            {
                return this.playTimeField;
            }
            set
            {
                this.playTimeField = value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection partName
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.partNameField);
            }
            set
            {
                this.partNameField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection comment
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.commentField);
            }
            set
            {
                this.commentField = value.Value;
            }
        }

        /// <remarks/>
        public stylePlugin stylePlugin
        {
            get
            {
                return this.stylePluginField;
            }
            set
            {
                this.stylePluginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("attr", IsNullable = false)]
        public typeParamAttr[] partStyle
        {
            get
            {
                return this.partStyleField;
            }
            set
            {
                this.partStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phraseStyle")]
        public phraseStyle[] phraseStyle
        {
            get
            {
                return this.phraseStyleField;
            }
            set
            {
                this.phraseStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("singer")]
        public singer[] singer
        {
            get
            {
                return this.singerField;
            }
            set
            {
                this.singerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mCtrl")]
        public mCtrl[] mCtrl
        {
            get
            {
                return this.mCtrlField;
            }
            set
            {
                this.mCtrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sCtrl")]
        public sCtrl[] sCtrl
        {
            get
            {
                return this.sCtrlField;
            }
            set
            {
                this.sCtrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("note")]
        public note[] note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class stylePlugin
    {

        private string stylePluginIDField;

        private string stylePluginNameField;

        private string versionField;

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection stylePluginID
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.stylePluginIDField);
            }
            set
            {
                this.stylePluginIDField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection stylePluginName
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.stylePluginNameField);
            }
            set
            {
                this.stylePluginNameField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection version
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.versionField);
            }
            set
            {
                this.versionField = value.Value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class phraseStyle
    {

        private int posTickField;

        private typeParamAttr[] attrField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr")]
        public typeParamAttr[] attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class singer
    {

        private int posTickField;

        private byte vBSField;

        private byte vPCField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public byte vBS
        {
            get
            {
                return this.vBSField;
            }
            set
            {
                this.vBSField = value;
            }
        }

        /// <remarks/>
        public byte vPC
        {
            get
            {
                return this.vPCField;
            }
            set
            {
                this.vPCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class mCtrl
    {

        private int posTickField;

        private typeParamAttr attrField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public typeParamAttr attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class sCtrl
    {

        private int posTickField;

        private typeParamAttr attrField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public typeParamAttr attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class note
    {

        private int posTickField;

        private int durTickField;

        private byte noteNumField;

        private byte velocityField;

        private string lyricField;

        private typePhonemes phnmsField;

        private noteStyle noteStyleField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public int durTick
        {
            get
            {
                return this.durTickField;
            }
            set
            {
                this.durTickField = value;
            }
        }

        /// <remarks/>
        public byte noteNum
        {
            get
            {
                return this.noteNumField;
            }
            set
            {
                this.noteNumField = value;
            }
        }

        /// <remarks/>
        public byte velocity
        {
            get
            {
                return this.velocityField;
            }
            set
            {
                this.velocityField = value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection lyric
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.lyricField);
            }
            set
            {
                this.lyricField = value.Value;
            }
        }

        /// <remarks/>
        public typePhonemes phnms
        {
            get
            {
                return this.phnmsField;
            }
            set
            {
                this.phnmsField = value;
            }
        }

        /// <remarks/>
        public noteStyle noteStyle
        {
            get
            {
                return this.noteStyleField;
            }
            set
            {
                this.noteStyleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class noteStyle
    {

        private typeParamAttr[] attrField;

        private seqAttr[] seqAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr")]
        public typeParamAttr[] attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seqAttr")]
        public seqAttr[] seqAttr
        {
            get
            {
                return this.seqAttrField;
            }
            set
            {
                this.seqAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class seqAttr
    {

        private seqAttrElem[] elemField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("elem")]
        public seqAttrElem[] elem
        {
            get
            {
                return this.elemField;
            }
            set
            {
                this.elemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    public partial class seqAttrElem
    {

        private int posNrmField;

        private int elvField;

        /// <remarks/>
        public int posNrm
        {
            get
            {
                return this.posNrmField;
            }
            set
            {
                this.posNrmField = value;
            }
        }

        /// <remarks/>
        public int elv
        {
            get
            {
                return this.elvField;
            }
            set
            {
                this.elvField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class prosodyPart
    {

        private int posTickField;

        private int playTimeField;

        private string partNameField;

        private string commentField;

        private voice[] voiceField;

        private pCtrl[] pCtrlField;

        private pch[] pchField;

        private dyn[] dynField;

        private phnm[] phnmField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public int playTime
        {
            get
            {
                return this.playTimeField;
            }
            set
            {
                this.playTimeField = value;
            }
        }

        /// <remarks/>
        public string partName
        {
            get
            {
                return this.partNameField;
            }
            set
            {
                this.partNameField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("voice")]
        public voice[] voice
        {
            get
            {
                return this.voiceField;
            }
            set
            {
                this.voiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pCtrl")]
        public pCtrl[] pCtrl
        {
            get
            {
                return this.pCtrlField;
            }
            set
            {
                this.pCtrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pch")]
        public pch[] pch
        {
            get
            {
                return this.pchField;
            }
            set
            {
                this.pchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dyn")]
        public dyn[] dyn
        {
            get
            {
                return this.dynField;
            }
            set
            {
                this.dynField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phnm")]
        public phnm[] phnm
        {
            get
            {
                return this.phnmField;
            }
            set
            {
                this.phnmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class voice
    {

        private int posSecField;

        private byte vBSField;

        private byte vPCField;

        /// <remarks/>
        public int posSec
        {
            get
            {
                return this.posSecField;
            }
            set
            {
                this.posSecField = value;
            }
        }

        /// <remarks/>
        public byte vBS
        {
            get
            {
                return this.vBSField;
            }
            set
            {
                this.vBSField = value;
            }
        }

        /// <remarks/>
        public byte vPC
        {
            get
            {
                return this.vPCField;
            }
            set
            {
                this.vPCField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class pCtrl
    {

        private int posSecField;

        private typeParamAttr attrField;

        /// <remarks/>
        public int posSec
        {
            get
            {
                return this.posSecField;
            }
            set
            {
                this.posSecField = value;
            }
        }

        /// <remarks/>
        public typeParamAttr attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class pch
    {

        private int posSecField;

        private int pchValField;

        /// <remarks/>
        public int posSec
        {
            get
            {
                return this.posSecField;
            }
            set
            {
                this.posSecField = value;
            }
        }

        /// <remarks/>
        public int pchVal
        {
            get
            {
                return this.pchValField;
            }
            set
            {
                this.pchValField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class dyn
    {

        private int posSecField;

        private int dynValField;

        /// <remarks/>
        public int posSec
        {
            get
            {
                return this.posSecField;
            }
            set
            {
                this.posSecField = value;
            }
        }

        /// <remarks/>
        public int dynVal
        {
            get
            {
                return this.dynValField;
            }
            set
            {
                this.dynValField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class phnm
    {

        private int posSecField;

        private int durSecField;

        private string phnmStrField;

        /// <remarks/>
        public int posSec
        {
            get
            {
                return this.posSecField;
            }
            set
            {
                this.posSecField = value;
            }
        }

        /// <remarks/>
        public int durSec
        {
            get
            {
                return this.durSecField;
            }
            set
            {
                this.durSecField = value;
            }
        }

        /// <remarks/>
        public string phnmStr
        {
            get
            {
                return this.phnmStrField;
            }
            set
            {
                this.phnmStrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class wavPart
    {

        private int posTickField;

        private int playTimeField;

        private string partNameField;

        private string commentField;

        private uint sampleRateField;

        private byte sampleResoField;

        private byte channelsField;

        private string filePathField;

        /// <remarks/>
        public int posTick
        {
            get
            {
                return this.posTickField;
            }
            set
            {
                this.posTickField = value;
            }
        }

        /// <remarks/>
        public int playTime
        {
            get
            {
                return this.playTimeField;
            }
            set
            {
                this.playTimeField = value;
            }
        }

        /// <remarks/>
        public string partName
        {
            get
            {
                return this.partNameField;
            }
            set
            {
                this.partNameField = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public uint sampleRate
        {
            get
            {
                return this.sampleRateField;
            }
            set
            {
                this.sampleRateField = value;
            }
        }

        /// <remarks/>
        public byte sampleReso
        {
            get
            {
                return this.sampleResoField;
            }
            set
            {
                this.sampleResoField = value;
            }
        }

        /// <remarks/>
        public byte channels
        {
            get
            {
                return this.channelsField;
            }
            set
            {
                this.channelsField = value;
            }
        }

        /// <remarks/>
        public string filePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class aux
    {

        private string auxIDField;

        private string contentField;

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection auxID
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.auxIDField);
            }
            set
            {
                this.auxIDField = value.Value;
            }
        }

        /// CDATAセクションに変更<remarks/>
        public XmlCDataSection content
        {
            get
            {
                return new XmlDocument().CreateCDataSection(this.contentField);
            }
            set
            {
                this.contentField = value.Value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class vVoiceTable
    {

        private vVoice[] vVoiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vVoice")]
        public vVoice[] vVoice
        {
            get
            {
                return this.vVoiceField;
            }
            set
            {
                this.vVoiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class partStyle
    {

        private typeParamAttr[] attrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attr")]
        public typeParamAttr[] attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class seTrack
    {

        private wavPart[] wavPartField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wavPart")]
        public wavPart[] wavPart
        {
            get
            {
                return this.wavPartField;
            }
            set
            {
                this.wavPartField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yamaha.co.jp/vocaloid/schema/vsq3/", IsNullable = false)]
    public partial class karaokeTrack
    {

        private wavPart[] wavPartField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wavPart")]
        public wavPart[] wavPart
        {
            get
            {
                return this.wavPartField;
            }
            set
            {
                this.wavPartField = value;
            }
        }
    }

}
